// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.conductor;

import "intrinsic/config/proto/operation_mode.proto";
import "intrinsic/util/status/extended_status.proto";

option go_package = "intrinsic/conductor/proto/execution_context_go_proto";

message ExecutionContext {
  config.OperationMode mode = 1;
  string belief_world_id = 2;
  string sim_world_id = 3;
  string staging_world_id = 4;
  string edit_world_id = 5;

  // If present, the status represents errors generarted when creating this
  // execution context from the application.
  optional intrinsic_proto.status.ExtendedStatus edit_world_status = 6;
}
