# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

package(
    default_visibility = ["//visibility:public"],
)

filegroup(
    name = "robotiq_hande",
    srcs = [
        "base_visual.glb",
        "flat_al_finger_visual.glb",
        "io_coupler_visual.glb",
        "jaw_l_visual.glb",
        "jaw_r_visual.glb",
        "robotiq_hande/model.config",
        "robotiq_hande/robotiq_hande.sdf",
        "robotiq_hande_no_fingers/model.config",
        "robotiq_hande_no_fingers/robotiq_hande_no_fingers.sdf",
    ],
)
