// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "intrinsic/icon/server/autogenerated_icon_config_service.h"

#include <memory>
#include <string>
#include <utility>

#include "absl/container/flat_hash_map.h"
#include "absl/status/statusor.h"
#include "absl/strings/string_view.h"
#include "absl/time/clock.h"
#include "absl/time/time.h"
#include "grpcpp/server.h"
#include "grpcpp/support/status.h"
#include "intrinsic/connect/cc/grpc/channel.h"
#include "intrinsic/icon/hal/hardware_interface_utils.h"
#include "intrinsic/icon/hal/proto/hardware_module_config.pb.h"
#include "intrinsic/icon/proto/v1/autogenerated_icon_config_service.pb.h"
#include "intrinsic/icon/server/auto_config_helpers.h"
#include "intrinsic/resources/client/resource_registry_client.h"
#include "intrinsic/resources/proto/resource_registry.pb.h"
#include "intrinsic/resources/proto/runtime_context.pb.h"
#include "intrinsic/util/proto/any.h"
#include "intrinsic/util/status/status_macros.h"
#include "intrinsic/util/status/status_macros_grpc.h"
#include "intrinsic/world/objects/object_world_client.h"
#include "intrinsic/world/proto/object_world_service.grpc.pb.h"

namespace intrinsic::icon {
namespace {

absl::StatusOr<absl::flat_hash_map<std::string, std::string>>
GetModuleNameToResourceNameMap(
    const resources::ResourceRegistryClient& resource_registry_client) {
  intrinsic_proto::resources::ListResourceInstanceRequest::StrictFilter filter;
  INTR_ASSIGN_OR_RETURN(auto resources,
                        resource_registry_client.ListResources(filter));
  absl::flat_hash_map<std::string, std::string> module_name_to_resource_name;
  for (const auto& resource : resources) {
    absl::StatusOr<intrinsic_proto::icon::HardwareModuleConfig> module_config =
        intrinsic::UnpackAny<intrinsic_proto::icon::HardwareModuleConfig>(
            resource.configuration());
    if (!module_config.ok()) {
      continue;
    }
    if (module_config->name().empty()) {
      module_name_to_resource_name[resource.name()] = resource.name();
    } else {
      module_name_to_resource_name[module_config->name()] = resource.name();
    }
  }
  return module_name_to_resource_name;
}

}  // namespace

AutoGeneratedIconConfigService::AutoGeneratedIconConfigService(
    absl::string_view shared_memory_namespace,
    absl::string_view world_service_address,
    std::string resource_registry_address)
    : shared_memory_namespace_(shared_memory_namespace),
      world_service_address_(world_service_address),
      resource_registry_address_(resource_registry_address) {};

::grpc::Status AutoGeneratedIconConfigService::GetAutoGeneratedIconConfig(
    ::grpc::ServerContext* context,
    const ::intrinsic_proto::icon::v1::AutoGeneratedIconConfigRequest* request,
    ::intrinsic_proto::icon::v1::AutoGeneratedIconConfigResponse* response) {
  INTR_ASSIGN_OR_RETURN_GRPC(
      std::unique_ptr<resources::ResourceRegistryClient>
          resource_registry_client,
      resources::CreateResourceRegistryClient(resource_registry_address_));

  INTR_ASSIGN_OR_RETURN_GRPC(
      auto module_name_to_resource_name,
      GetModuleNameToResourceNameMap(*resource_registry_client));

  INTR_ASSIGN_OR_RETURN_GRPC(
      auto modules_and_names_with_types,
      hal::FindModulesAndInterfacesWithTypes(shared_memory_namespace_));

  INTR_ASSIGN_OR_RETURN_GRPC(auto world_channel,
                             connect::CreateClientChannel(
                                 world_service_address_,
                                 /*deadline=*/absl::Now() + absl::Seconds(10)));

  std::shared_ptr<intrinsic_proto::world::ObjectWorldService::StubInterface>
      object_world_service_stub =
          intrinsic_proto::world::ObjectWorldService::NewStub(world_channel);

  world::ObjectWorldClient object_world_client(request->world_id(),
                                               object_world_service_stub);

  // Make sure that our ObjectWorldClient actually works.
  INTR_RETURN_IF_ERROR_GRPC(object_world_client.GetRootObject().status());

  // Remove all modules that do not have an associated asset in the resource
  // registry. This is because leftover hardware interfaces may be included in
  // `modules_and_names_with_types`.
  absl::erase_if(modules_and_names_with_types,
                 [&](std::pair<const std::string,
                               absl::flat_hash_map<std::string, std::string>>&
                         module_and_interfaces) {
                   return !module_name_to_resource_name.contains(
                       module_and_interfaces.first);
                 });

  INTR_ASSIGN_OR_RETURN_GRPC(
      auto autogenerated_config,
      AutoGenerateIconConfig(modules_and_names_with_types,
                             module_name_to_resource_name,
                             *resource_registry_client, object_world_client));

  *response->mutable_autogenerated_icon_main_config() = autogenerated_config;

  return grpc::Status::OK;
}

}  // namespace intrinsic::icon
