// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef INTRINSIC_ICON_SERVER_AUTOGENERATED_ICON_CONFIG_SERVICE_H_
#define INTRINSIC_ICON_SERVER_AUTOGENERATED_ICON_CONFIG_SERVICE_H_

#include <string>

#include "absl/strings/string_view.h"
#include "grpcpp/server.h"
#include "grpcpp/support/status.h"
#include "intrinsic/icon/proto/v1/autogenerated_icon_config_service.grpc.pb.h"
#include "intrinsic/icon/proto/v1/autogenerated_icon_config_service.pb.h"

namespace intrinsic::icon {

// Service running in an ICON instance that can be used to get an autogenerated
// IconMainConfig for that instance based on the current hardware modules
// deployed to the same node.
class AutoGeneratedIconConfigService
    : public ::intrinsic_proto::icon::v1::AutoGeneratedIconConfigService::
          Service {
 public:
  // Creates a new AutoGeneratedIconConfigService.
  // `shared_memory_namespace` is the memory namespace (which is a prefix on the
  // shared memory segment names) used to find interfaces. The
  // `world_service_address` is used to get the world from which the config is
  // generated.
  // `resource_registry_address` is used to get the hardware module asset
  // configurations.
  AutoGeneratedIconConfigService(absl::string_view shared_memory_namespace,
                                 absl::string_view world_service_address,
                                 std::string resource_registry_address);

  ::grpc::Status GetAutoGeneratedIconConfig(
      ::grpc::ServerContext* context,
      const ::intrinsic_proto::icon::v1::AutoGeneratedIconConfigRequest*
          request,
      ::intrinsic_proto::icon::v1::AutoGeneratedIconConfigResponse* response)
      override;

 private:
  std::string shared_memory_namespace_;
  std::string world_service_address_;
  std::string resource_registry_address_;
};

}  // namespace intrinsic::icon

#endif  // INTRINSIC_ICON_SERVER_AUTOGENERATED_ICON_CONFIG_SERVICE_H_
