// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef INTRINSIC_ICON_SERVER_GRPC_ENVELOPE_H_
#define INTRINSIC_ICON_SERVER_GRPC_ENVELOPE_H_

#include <functional>
#include <memory>
#include <optional>
#include <string>

#include "absl/base/attributes.h"
#include "absl/base/nullability.h"
#include "absl/base/thread_annotations.h"
#include "absl/status/status.h"
#include "absl/status/statusor.h"
#include "absl/strings/string_view.h"
#include "absl/synchronization/mutex.h"
#include "absl/synchronization/notification.h"
#include "grpcpp/channel.h"
#include "grpcpp/server.h"
#include "grpcpp/support/channel_arguments.h"
#include "intrinsic/hardware/gpio/v1/gpio_service.grpc.pb.h"
#include "intrinsic/icon/proto/v1/autogenerated_icon_config_service.grpc.pb.h"
#include "intrinsic/icon/proto/v1/jogging_service.grpc.pb.h"
#include "intrinsic/icon/server/icon_api_service.h"
#include "intrinsic/util/thread/stop_token.h"
#include "intrinsic/util/thread/thread.h"

namespace intrinsic::icon {

// Interface that wraps implementations of the ICON and GPIO services.
//
// `GrpcEnvelope` relays requests to these two services, unless there is an
// error. If there *is* an error, `GrpcEnvelope` reports that error as a
// response to any and all gRPC requests. There are two exceptions to this
// behavior:
//
// * If a client calls `IconApiService::RestartServer()`, then `GrpcEnvelope`
//   discards the `IconImplInterface` and builds a new one, effectively
//   restarting ICON.
// * If a client calls `IconApiService::ClearFaults()`
//   *while `IconImplInterface::Status()` is not `absl::OkStatus()`*, then
//   `GrpcEnvelope` also discards the `IconImplInterface` and builds a new one.
//
// (Note that in both of these cases, the gRPC call blocks until the replacement
// `IconImplInterface` is ready.)
class IconImplInterface {
 public:
  virtual ~IconImplInterface() = default;
  // Returns a pointer to an ICON gRPC service. This reference must be valid
  // for the lifetime of the IconImplInterface.
  //
  // Returns an error if the IconImplInterface is in an error state.
  virtual absl::StatusOr<icon::IconApiService* absl_nonnull> IconService()
      ABSL_ATTRIBUTE_LIFETIME_BOUND = 0;
  // Returns a pointer to a GPIOService. This reference must be valid for the
  // lifetime of the IconImplInterface.
  //
  // Returns an error if the IconImplInterface is in an error state.
  virtual absl::StatusOr<
      intrinsic_proto::gpio::v1::GPIOService::Service* absl_nonnull>
  GpioService() ABSL_ATTRIBUTE_LIFETIME_BOUND = 0;

  // Returns a pointer to a JoggingService. This reference must be valid for
  // the lifetime of the IconImplInterface.
  //
  // Returns an error if the IconImplInterface is in an error state.
  virtual absl::StatusOr<
      intrinsic_proto::icon::v1::JoggingService::Service* absl_nonnull>
  JoggingService() ABSL_ATTRIBUTE_LIFETIME_BOUND = 0;
};

// A wrapper for the ICON, GPIO grpc services and handler for the realtime
// tracing service. They either forwards calls to the wrapped services `service`
// and `gpio_service` or responds to all calls with a global error `status`.
// Each grpc server is started when the first setter function is called.
// The purpose of this is to expose error messages longer.

// Realtime tracing calls are handled directly in the wrapper to be able to
// trace ICON even if fatal errors occurred.

class GrpcEnvelope {
 public:
  struct Config {
    // Listening address of the gRPC services that GrpcEnvelope exposes:
    // * ICON Application Layer
    // * GPIO
    // * AutoGeneratedIconConfigService (if present in config)

    // * RealtimeTracingApi (if present in config)

    //
    // If unset, GrpcEnvelope still brings up the gRPC server, but the server is
    // only accessible via GrpcEnvelope::InProcChannel()
    const std::optional<std::string> grpc_address = std::nullopt;

    std::unique_ptr<
        ::intrinsic_proto::icon::v1::AutoGeneratedIconConfigService::Service>
        auto_config_service = nullptr;

    // Factory function for `IconImplInterface`. GrpcEnvelope builds and
    // replaces IconImplInterface as needed at runtime (see documentation on
    // IconImplInterface for more details).
    std::function<absl::StatusOr<std::unique_ptr<IconImplInterface>>()>
        icon_impl_factory;
    // Callback when the ICON server is shutting down for a restart.
    // `RebuildIconImpl()` calls this after the ICON instance has been
    // destroyed. Can be left empty if no additional shutdown tasks are needed.
    std::function<absl::Status()> icon_shutdown_for_restart_callback;
    std::string icon_name;
  };

  explicit GrpcEnvelope(Config config);

  ~GrpcEnvelope();

  // Calls "TryCancel" on gRPC streams.
  // Usually results in all sessions closing later (after this call returns),
  // but this is not guaranteed (because of service methods not finishing for
  // other reasons or new grpc requests coming in).
  void TryCancelAllStreams();

  // 'nullptr' if ICON server has not started.
  std::shared_ptr<grpc::Channel> InProcChannel(
      const grpc::ChannelArguments& channel_args);

  // Blocks until shutdown.
  void Wait();

 private:
  class WrapperService;
  class IconHealthService;
  class GpioWrapperService;
  class RealtimeTracingService;
  class JoggingWrapperService;

  void StartServer();

  absl::StatusOr<IconApiService* absl_nonnull> IconService()
      ABSL_SHARED_LOCKS_REQUIRED(icon_impl_mutex_);
  absl::StatusOr<intrinsic_proto::gpio::v1::GPIOService::Service* absl_nonnull>
  GpioService() ABSL_SHARED_LOCKS_REQUIRED(icon_impl_mutex_);

  absl::StatusOr<
      intrinsic_proto::icon::v1::JoggingService::Service* absl_nonnull>
  JoggingService() ABSL_SHARED_LOCKS_REQUIRED(icon_impl_mutex_);

  // Tears down the current IconImplInterface and uses the factory in `config_`
  // to build a new one.
  //
  // Forwards any errors from the factory, and sets `icon_impl_`, regardless of
  // whether the factory succeeded or failed.
  absl::Status RebuildIconImpl() ABSL_LOCKS_EXCLUDED(icon_impl_mutex_);

  // This function acts as a "watchdog" for the health of `icon_impl_`, and
  // publishes messages to the robot_status PubSub topics if `icon_impl_` is
  // unhealthy.
  //
  // There are two situations where we consider ICON to be unhealthy:
  // 1. `icon_impl_.ok() == false` (i.e. we encountered an error calling the
  //    ICON factory)
  // 2. `icon_impl_.value()->IconService()` returns an error (i.e. ICON
  //    encountered a fatal fault during operation)
  //
  // Publishes a LogItem with a RobotStatus on the two PubSub topics
  // for the ICON server (full rate and throttled) every
  // `kErrorStatusPublishPeriodSeconds`, until `stop_token` requests a stop.
  //
  // The `RobotStatus` contains a `FAULTED` `OperationalStatus` with the message
  // from `error_status`.
  //
  //  This is helpful because some clients do not use `GetOperationalStatus()`
  //  to retrieve the current operational status, but rather subscribe to these
  //  PubSub topics. In case of an init fault, we should keep these clients
  //  informed of the operational status by publishing values here.
  void PublishErrorStatusLoop(const intrinsic::StopToken& stop_token);
  const Config config_;

  mutable absl::Mutex icon_impl_mutex_;
  absl::StatusOr<std::unique_ptr<IconImplInterface>> icon_impl_ ABSL_GUARDED_BY(
      icon_impl_mutex_) = absl::UnavailableError("Service is not set yet");

  std::unique_ptr<WrapperService> wrapper_service_;
  std::unique_ptr<IconHealthService> icon_health_service_;
  std::unique_ptr<GpioWrapperService> gpio_wrapper_service_;

  std::unique_ptr<JoggingWrapperService> jogging_wrapper_service_;
  // Not a wrapper, as tracing does not need the same sort of "service
  // injection".
  // Since RealtimeTracingService is defined in the .cc file, this
  // must be a unique_ptr (a plain object instance would fail to initialize
  // because the type is incomplete given just the header)
  std::unique_ptr<RealtimeTracingService> rt_tracing_service_;

  std::unique_ptr<::grpc::Server> server_;
  absl::Notification stop_error_status_thread_;
  intrinsic::Thread publish_error_status_thread_;
};

}  // namespace intrinsic::icon

#endif  // INTRINSIC_ICON_SERVER_GRPC_ENVELOPE_H_
