// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include <unistd.h>

#include <csignal>
#include <cstdint>
#include <cstdlib>
#include <memory>
#include <optional>
#include <string>
#include <vector>

#include "absl/flags/flag.h"
#include "absl/functional/bind_front.h"
#include "absl/log/check.h"
#include "absl/log/log.h"
#include "absl/status/status.h"
#include "absl/status/statusor.h"
#include "absl/strings/str_cat.h"
#include "absl/strings/string_view.h"
#include "absl/time/clock.h"
#include "absl/time/time.h"
#include "absl/types/span.h"
#include "grpcpp/health_check_service_interface.h"
#include "intrinsic/assets/dependencies/utils.h"
#include "intrinsic/assets/proto/status_spec.pb.h"
#include "intrinsic/assets/services/proto/v1/service_state.pb.h"
#include "intrinsic/connect/cc/grpc/channel.h"
#include "intrinsic/icon/release/file_helpers.h"
#include "intrinsic/icon/release/portable/init_intrinsic.h"
#include "intrinsic/icon/server/autogenerated_icon_config_service.h"
#include "intrinsic/icon/server/config/icon_main_config.pb.h"
#include "intrinsic/icon/server/extended_status_constants.h"
#include "intrinsic/icon/server/grpc_envelope.h"
#include "intrinsic/icon/server/icon_main_loop_factory.h"
#include "intrinsic/icon/server/runtime_options.h"
#include "intrinsic/icon/utils/shutdown_signals.h"
#include "intrinsic/logging/data_logger_client.h"
#include "intrinsic/logging/proto/logger_service.grpc.pb.h"
#include "intrinsic/resources/proto/resource_registry.pb.h"
#include "intrinsic/resources/proto/runtime_context.pb.h"
#include "intrinsic/stats/opencensus.h"
#include "intrinsic/util/memory_lock.h"
#include "intrinsic/util/proto/any.h"
#include "intrinsic/util/proto/get_text_proto.h"
#include "intrinsic/util/proto/parse_text_proto.h"
#include "intrinsic/util/status/return.h"
#include "intrinsic/util/status/status_macros.h"
#include "intrinsic/util/status/status_specs.h"

ABSL_FLAG(
    std::string, config_pbtxt_file, "",
    "ICON server configuration file path. If no config file is specified ICON "
    "is trying to obtain its configuration from the resource context.");

// TODO(b/288415492): Remove this flag from here and usage site. It duplicates
// server_name.
ABSL_FLAG(std::string, robot, "robot",
          "Server name. Used in certain pubsub messages, among other uses.");

// Formerly, "--robot".
ABSL_FLAG(std::string, server_name, "robot",
          "Server name. This is used to uniquely identify a single realtime "
          "control server. The server name shows up in logs and determines the "
          "names of DDS topics, among other things. ");

ABSL_FLAG(std::string, resource_id, "",
          "Intrinsic Resource ID. If empty, ICON assumes it is not running as "
          "a resource instance.");

ABSL_FLAG(bool, non_realtime, false,
          "Run the server in non-realtime mode. This makes the main loop *not* "
          "impose any hard cycle timeouts in case of overruns. This still "
          "requires to connect to a hardware module which may implement "
          "loopback, physics simulation or real hardware.");

ABSL_FLAG(uint16_t, icon_server_port, 0,
          "Port for the ICON sercer. 0 builds an in-process server without "
          "ports exposed. An often chosen port is 8128.");
ABSL_FLAG(std::string, shared_memory_namespace_testonly, "",
          "Prefix for all shared memory connections. Passing unique namespace "
          "is needed to make integration tests hermetic.");

ABSL_FLAG(absl::Duration, grpc_client_connection_timeout,
          intrinsic::connect::kGrpcClientConnectDefaultTimeout,
          "Time to wait for the grpc server to become available.");

ABSL_FLAG(
    std::string, resource_registry_service,
    "istio-ingressgateway.app-ingress.svc.cluster.local:80",
    "Address of the ResourceRegistry gRPC server, in 'hostname:port' format");

// TODO(b/549476229): Fallback was added for Asset migration; consider removing
// this flag once all ICON instances in solutions populate the
// intrinsic_runtime config parameter.
ABSL_FLAG(bool, use_runtime_asset_fallback, true,
          "Whether to use asset runtime fallback when connecting to "
          "dependency services.");

const char* UsageString() {
  return R"(
Usage: icon_main [--config_pbtxt_file=<path>] [--server_name=<name>] [--non_realtime] [--icon_server_port 8128]

Runs an ICON Server with the specified configuration.
)";
}

namespace intrinsic::icon {
namespace {
constexpr absl::Duration kPollShutdownSignalEvery = absl::Milliseconds(250);

void PluginDirectoryFromConfigProto(
    const intrinsic_proto::icon::IconMainConfig& config,
    intrinsic::icon::ServerRuntimeOptions& server_runtime_options) {
  std::string plugin_dir = "/mnt/local-uploads";

  if (config.has_plugin_loading_config()) {
    if (config.plugin_loading_config().has_plugin_dir_override() &&
        !config.plugin_loading_config().plugin_dir_override().empty()) {
      plugin_dir = config.plugin_loading_config().plugin_dir_override();
    }
    server_runtime_options.plugin_dir = plugin_dir;
    LOG(INFO) << "Plugin dir: " << plugin_dir;
  }
}

absl::StatusOr<intrinsic_proto::icon::IconMainConfig> LoadMainConfigFromFile(
    absl::string_view config_pbtxt_file) {
  intrinsic_proto::icon::IconMainConfig config;
  INTR_RETURN_IF_ERROR(
      intrinsic::internal::GetTextProtoPortable(config_pbtxt_file, config));
  return config;
}

absl::StatusOr<MainLoopConfiguration> ConfigurationFromFlags() {
  MainLoopConfiguration configuration;
  INTR_ASSIGN_OR_RETURN(
      configuration.config,
      LoadMainConfigFromFile(absl::GetFlag(FLAGS_config_pbtxt_file)));
  configuration.server_runtime_options.server_name =
      absl::GetFlag(FLAGS_server_name);
  configuration.server_runtime_options.resource_id =
      absl::GetFlag(FLAGS_resource_id);

  if (absl::GetFlag(FLAGS_non_realtime)) {
    configuration.server_runtime_options.mode =
        intrinsic::icon::ServerRuntimeMode::kNonRealtime;
  } else {
    configuration.server_runtime_options.mode =
        intrinsic::icon::ServerRuntimeMode::kNormal;
  }

  configuration.icon_server_port = absl::GetFlag(FLAGS_icon_server_port);

  return configuration;
}

// Parses the runtime context (IconMainConfig, icon_server_port (also required
// for the gRPC envelope), server_runtime_options) into a Configuration.
//
// Returns an error on issues with the RuntimeContext.
// Returns an error if parsing the IconMainConfig fails.
absl::StatusOr<MainLoopConfiguration> ConfigurationFromResourceContext() {
  constexpr absl::string_view kContextFilePath =
      "/etc/intrinsic/runtime_config.pb";

  INTR_ASSIGN_OR_RETURN(
      auto context,
      GetBinaryProto<intrinsic_proto::config::RuntimeContext>(kContextFilePath),
      _ << "Reading runtime context");

  MainLoopConfiguration configuration;
  configuration.icon_server_port = context.port();
  if (configuration.icon_server_port == 0) {
    return absl::InvalidArgumentError("Missing resource port");
  }

  configuration.config =
      UnpackAny<intrinsic_proto::icon::IconMainConfig>(context.config());
  if (!configuration.config.ok()) {
    LOG(ERROR) << "Failed to unpack IconMainConfig: "
               << configuration.config.status();
  }

  const std::string& resource_id = context.name();
  configuration.server_runtime_options.resource_id = resource_id;
  configuration.server_runtime_options.server_name = resource_id;

  switch (context.level()) {
    case intrinsic_proto::config::RuntimeContext::REALITY: {
      configuration.server_runtime_options.mode =
          intrinsic::icon::ServerRuntimeMode::kNormal;
      break;
    }
    case intrinsic_proto::config::RuntimeContext::PHYSICS_SIM: {
      configuration.server_runtime_options.mode =
          intrinsic::icon::ServerRuntimeMode::kNonRealtime;
      break;
    }
    case intrinsic_proto::config::RuntimeContext::UNSPECIFIED:
    default:
      return absl::InvalidArgumentError(
          absl::StrCat("Unknown level in runtime context: ",
                       intrinsic_proto::config::RuntimeContext::Level_Name(
                           context.level())));
      break;
  }

  return configuration;
}

absl::StatusOr<intrinsic::icon::MainLoopConfiguration> LoadConfiguration() {
  LOG(INFO) << "Reading ICON config.";
  intrinsic::icon::MainLoopConfiguration configuration;

  // Only try loading the config from resource config if no pbtxt file is passed
  // in.
  if (!absl::GetFlag(FLAGS_config_pbtxt_file).empty()) {
    INTR_ASSIGN_OR_RETURN(configuration,
                          intrinsic::icon::ConfigurationFromFlags());
  } else {
    LOG(INFO) << "Parsing IconMainConfig from Resource Context because "
                 "'--config_pbtxt_file' is empty.";
    const auto config_or = intrinsic::icon::ConfigurationFromResourceContext();

    if (!config_or.ok()) {
      // Something is wrong with the runtime context. Aborting.
      return absl::NotFoundError(
          absl::StrCat("Unable to obtain configuration from runtime context: ",
                       config_or.status().message()));
    }
    configuration = config_or.value();
  }
  configuration.resource_registry_address =
      absl::GetFlag(FLAGS_resource_registry_service);
  configuration.shared_memory_namespace =
      absl::GetFlag(FLAGS_shared_memory_namespace_testonly);
  configuration.use_runtime_asset_fallback =
      absl::GetFlag(FLAGS_use_runtime_asset_fallback);

  if (configuration.config.ok()) {
    intrinsic::icon::PluginDirectoryFromConfigProto(
        *configuration.config, configuration.server_runtime_options);
  }

  return configuration;
}

void InitializeDataLogger(const MainLoopConfiguration& configuration) {
  if (!configuration.config.ok()) {
    return;
  }
  constexpr char kDataLoggerInterface[] =
      "grpc://intrinsic_proto.data_logger.DataLogger";
  absl::StatusOr<std::shared_ptr<grpc::Channel>> data_logger_channel;
  if (configuration.use_runtime_asset_fallback) {
    data_logger_channel = intrinsic::assets::dependencies::
        ConnectWithRuntimeAssetFallbackForAssetMigrationOnly(
            configuration.config->intrinsic_runtime(), kDataLoggerInterface,
            connect::UnlimitedMessageSizeGrpcChannelArgs());
  } else if (configuration.config->intrinsic_runtime().interfaces().contains(
                 kDataLoggerInterface)) {
    data_logger_channel = intrinsic::assets::dependencies::Connect(
        configuration.config->intrinsic_runtime(), kDataLoggerInterface,
        connect::UnlimitedMessageSizeGrpcChannelArgs());
  }
  if (data_logger_channel.ok()) {
    if (auto status = intrinsic::connect::WaitForChannelReady(
            *data_logger_channel,
            absl::GetFlag(FLAGS_grpc_client_connection_timeout));
        !status.ok()) {
      LOG(ERROR) << "Failed to connect to data logger: " << status;
    } else {
      auto data_logger_stub = intrinsic_proto::data_logger::DataLogger::NewStub(
          *data_logger_channel);
      if (auto s = intrinsic::data_logger::StartUpIntrinsicLoggerViaStub(
              std::move(data_logger_stub));
          !s.ok()) {
        LOG(ERROR) << "Failed to connect to data logger: " << s;
      }
    }
  }
}

absl::Status Main(const MainLoopConfiguration& configuration) {
  // Ignore SIGPIPEs.
  // They usually are false positives and will be accompanied by EPIPE when
  // truly a failure.
  std::signal(SIGPIPE, SIG_IGN);
  // Handle SIGTERM, sent by Kubernetes to shut down.
  std::signal(SIGTERM, ShutdownSignalHandler);
  // Handle Ctrl+C to shut down.
  std::signal(SIGINT, ShutdownSignalHandler);

  constexpr int process_memory = 256 * 1024;
  INTR_RETURN_IF_ERROR(
      (intrinsic::LockMemory<process_memory, process_memory>()))
          .LogError()
      << "Failed to lock memory";

  int icon_server_port = configuration.icon_server_port;
  std::optional<std::string> icon_server_address;
  if (icon_server_port != 0) {
    icon_server_address = absl::StrCat("0.0.0.0:", icon_server_port);
  }

  LOG(INFO) << "Address: " << icon_server_address.value_or("") << ".";

  std::string world_service_address;
  if (configuration.config.ok()) {
    const auto& interfaces =
        configuration.config->intrinsic_runtime().interfaces();
    auto it =
        interfaces.find("grpc://intrinsic_proto.world.ObjectWorldService");
    if (it != interfaces.end()) {
      world_service_address = it->second.grpc().connection().address();
    }
  }

  GrpcEnvelope grpc_envelope({
      .grpc_address = icon_server_address,
      .auto_config_service = std::make_unique<AutoGeneratedIconConfigService>(
          configuration.shared_memory_namespace, world_service_address,
          configuration.resource_registry_address),
      .icon_impl_factory =
          absl::bind_front(IconMainLoopImplFactory, configuration),
      .icon_shutdown_for_restart_callback =
          [  // Copy the config object into the lambda so that it lives as long
             // the lambda is alive.
              configuration] {
            std::vector<std::string> hardware_module_names(
                configuration.config->hardware_module_names().begin(),
                configuration.config->hardware_module_names().end());
            return IconMainLoopShutdownForRestart(
                absl::MakeConstSpan(hardware_module_names),
                configuration.shared_memory_namespace);
          },
      .icon_name = configuration.server_runtime_options.server_name,
  });

  while (IsShutdownRequested() == ShutdownType::kNotRequested) {
    absl::SleepFor(kPollShutdownSignalEvery);
  }
  LOG(INFO) << "Received shutdown request, stopping ICON server";
  // The destructors of GrpcEnvelope and MainLoopImpl do all of the cleanup work
  // (stopping both the gRPC server and ICON realtime server)
  return absl::OkStatus();
}

}  // namespace
}  // namespace intrinsic::icon

int main(int argc, char** argv) {
  InitIntrinsic(UsageString(), argc, argv);

  // Connect to the DataLogger if the endpoint is configured. Do not
  // fail if the logger is unavailable.
  // Start the OpenCensus plugin needed by the DataLogger.
  intrinsic::OpenCensusPlugin plugin;

  intrinsic_proto::assets::StatusSpecs specs =
      intrinsic::ParseTextProtoOrDie(intrinsic::icon::kStatusSpecs);
  INTR_RETURN_IF_ERROR(
      intrinsic::InitExtendedStatusSpecs(
          intrinsic::icon::kExtendedStatusComponent, specs.status_info()))
      .LogError()
      .With(intrinsic::Return(EXIT_FAILURE));

  INTR_ASSIGN_OR_RETURN(const auto configuration,
                        intrinsic::icon::LoadConfiguration(),
                        _.LogError().With(intrinsic::Return(EXIT_FAILURE)));

  intrinsic::icon::InitializeDataLogger(configuration);

  grpc::EnableDefaultHealthCheckService(true);
  LOG(INFO) << "Set health check.";

  absl::Status main_result = intrinsic::icon::Main(configuration);
  if (!main_result.ok()) {
    LOG(ERROR) << "ICON main failed: " << main_result;
    return EXIT_FAILURE;
  }
  return EXIT_SUCCESS;
}
