// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.executive;

import "intrinsic/executive/proto/behavior_tree.proto";

option go_package = "intrinsic/executive/proto/process_tree_go_proto";

// The Process Behavior Tree (process tree or pBT) is the user-defined process.
// It is the BT that a user can upload and control unlike system trees, which
// operate in the background.
//
// This message is stored in the process blackboard key such that system trees
// can inspect the state of a process tree.
message ProcessTreeState {
  // State of the Behavior Tree, if UNSPECIFIED no tree has been loaded, yet.
  BehaviorTree.State state = 1;

  string name = 2;
}
