// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto;

option go_package = "intrinsic/math/proto/bspline_go_proto";

// Representation of a B-Spline.
message BSpline {
  message ControlPoint {
    // The point coordinates.
    repeated double point = 1;
  }

  // The degree of the B-spline.
  int32 degree = 1;
  // The size of each of the control points.
  int32 control_point_size = 2;
  // The knots of the B-spline.
  repeated double knots = 3;
  // The control points of the B-spline.
  repeated ControlPoint control_points = 4;
}
