// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef INTRINSIC_MATH_SIGNALS_ADAPTIVE_QUADRATURE_H_
#define INTRINSIC_MATH_SIGNALS_ADAPTIVE_QUADRATURE_H_

// A library for numerically integrating functions via adaptive quadrature.
// Adaptive quadrature is a numerical integration method where a base
// quadrature rule is applied on adaptively refined subintervals of the
// integration domain (https://en.wikipedia.org/wiki/Adaptive_quadrature). The
// creation of new subintervals is based on an estimation of the integration
// error over the existing subintervals. Thus, adaptive quadrature algorithms
// are in general just as efficient and effective as the base quadrature rule
// for "well behaved" integrands, but their interval subdivsion scheme allows
// them to be more effective also in areas of the integration domain where the
// integrand is "badly behaved". However, the number of subdivisions and the
// final level of accuracy achieved in such areas will eventually depend on how
// the underlying base quadrature rule handles the kind of criticalities that
// the integrand may exhibit.
// The method implemented in this library relies on nested quadrature rules as
// base rules. These quadrature rules directly return an estimation of the
// integration error as part of their result. At each new iteration of the
// implemented algorithm, the subinterval with the largest error estimate is
// split, and the process is repeated until one of the terminal conditions is
// met. This guarantees that the algorithm always focuses on the most critical
// regions first.

#include <list>

#include "absl/functional/function_ref.h"
#include "absl/status/statusor.h"
#include "intrinsic/math/signals/nested_quadrature.h"

namespace intrinsic {

// A struct to hold the parameters controlling the behavior of the adaptive
// quadrature algorithm.
struct AdaptiveQuadratureOptions {
  // The desired absolute integration error. The adaptive quadrature algorithm
  // will stop if the integration error estimate is smaller than this value.
  double desired_absolute_error = 1e-8;

  // The desired relative integration error. The adaptive quadrature algorithm
  // will stop if the integration error estimate is smaller than this value
  // multiplied by the module of the integral itself.
  double desired_relative_error = 1e-6;

  // The maximum number of subintervals that can be generated. The computation
  // will stop when this limit is reached.
  int max_num_subintervals = 200;

  // The maximum subinterval depth that can be reached. The computation will
  // stop when this limit is reached.
  int max_subinterval_depth = 20;
};

// A struct collecting all data related to a subinterval generated by the
// adaptive quadrature.
struct AdaptiveQuadratureSubinterval {
  double start;           // The start of the subinterval.
  double end;             // The end of the subinterval.
  double integral;        // The integral computed over the subinterval.
  double error_estimate;  // The integration error estimate computed over the
                          // subinterval.
  int depth;  // The depth of the subinterval. This is the number of splits
              // required to generate this subinterval from the original
              // integration interval.
};

// The result of an adaptive quadrature call.
struct AdaptiveQuadratureResult {
  // The integration result. This is the sum of all the subinterval integrals.
  double integral;

  // The estimated integration error. This is the sum of all the subinterval
  // error estimates.
  double error_estimate;

  // The depth of the deepest subinterval(s) generated by the adaptive
  // quadrature algorithm.
  int max_subinterval_depth_reached;

  // The data of all the subintervals generated by the adaptive quadrature
  // algorithm.
  std::list<AdaptiveQuadratureSubinterval> subinterval_results;
};

// Performs adaptive quadrature with the given `nested_quadrature_rule` as base
// rule to compute the integral of the provided `function` over the integration
// interval [`start`, `end`].  The algorithm iteratively splits the integration
// subinterval with the largest error estimate until one of the following
// conditions is met:
// - The `options.desired_absolute_error` is achieved. This means that the
//   `error_estimate` for the integral `I` over the interval [`start`, `end`] is
//   smaller than `options.desired_absolute_error`.
// - The `options.desired_relative_error` is achieved. This means that the
//   `error_estimate` for the integral `I` over the interval [`start`, `end`] is
//   such that: `error_estimate < |I| * options.desired_relative_error`.
// - The `options.max_num_subintervals` is reached. The original integration
//   interval [`start`, `end`] has been subdivided into
//   `options.max_num_subintervals` subintervals.
// - The `options.max_subinterval_depth` is reached. The depth of a subinterval
//   is the number of splits required to generate the subinterval from the
//   original integration interval. As such, the original integration interval
//   [`start`, `end`] has zero depth, and will be split into two subintervals
//   of depth 1 at the first iteration (should no terminal condition be met
//   yet).
// - The subinterval with the largest error estimate cannot be split further due
//   to machine precision limitations.
// When one of the terminal conditions is met, the algorithm stops and returns
// the results computed up to that point.
absl::StatusOr<AdaptiveQuadratureResult> AdaptiveQuadrature(
    const NestedQuadratureRule& nested_quadrature_rule,
    absl::FunctionRef<absl::StatusOr<double>(double)> function, double start,
    double end, const AdaptiveQuadratureOptions& options = {});

}  // namespace intrinsic

#endif  // INTRINSIC_MATH_SIGNALS_ADAPTIVE_QUADRATURE_H_
