# proto-file: intrinsic/skills/proto/skill_manifest.proto
# proto-message: Manifest

# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


id {
  package: "ai.intrinsic"
  name: "clear_motion_planner_service_cache"
}
display_name: "Clear Motion Planner Service Cache"
vendor {
  display_name: "Intrinsic"
}
documentation: {
  description:
    "Clear the motion planner service cache.\n"
    "Do not use this skill in parallel with any other skill.\n"
}
options {
  supports_cancellation: false
  python_config {
    skill_module: "incode.motion_planning.skills.clear_motion_planner_service_cache"
    proto_module: "incode.motion_planning.skills.clear_motion_planner_service_cache_pb2"
    create_skill: "incode.motion_planning.skills.clear_motion_planner_service_cache.ClearMotionPlannerServiceCache"
  }
}
parameter {
  message_full_name: "intrinsic_proto.skills.ClearMotionPlannerServiceCacheParams"
}
