// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package runtimeasset contains functions that generate the runtime asset.
package runtimeasset

import (
	"fmt"
	"os"
	"strings"

	"intrinsic/assets/conversion/runtime"
	"intrinsic/assets/dependencies/platform"
	"intrinsic/assets/idutils"
	"intrinsic/assets/interfaceutils"

	atypepb "intrinsic/assets/proto/asset_type_go_proto"
	documentationpb "intrinsic/assets/proto/documentation_go_proto"
	idpb "intrinsic/assets/proto/id_go_proto"
	iapb "intrinsic/assets/proto/installed_assets_go_proto"
	mpb "intrinsic/assets/proto/metadata_go_proto"
	aipb "intrinsic/assets/proto/v1/asset_instances_go_proto"
	gcpb "intrinsic/assets/proto/v1/grpc_connection_go_proto"
	icpb "intrinsic/assets/proto/v1/instance_config_go_proto"
	vendorpb "intrinsic/assets/proto/vendor_go_proto"
	rhpb "intrinsic/resources/proto/resource_handle_go_proto"
	resourcepb "intrinsic/resources/proto/resource_registry_go_proto"

	"google.golang.org/protobuf/types/known/anypb"
)

const (
	ingressAddress      = "istio-ingressgateway.app-ingress.svc.cluster.local:80"
	assetInstanceHeader = "x-resource-instance-name"
)

// GetVersion retrieves the runtime Asset's version string from a file, typically generated via
// expand_template. This provides an alternative to build.Label() for binaries used as Bazel
// tools, where build-time stamping is disabled in the exec configuration. If the file is empty,
// it falls back to an autogenerated version.
func GetVersion(versionFile string) (string, error) {
	data, err := os.ReadFile(versionFile)
	if err != nil {
		return "", fmt.Errorf("could not read version file: %v", err)
	}
	// Read the version file that was generated by expand_template.
	if v := strings.TrimSpace(string(data)); v != "" {
		if err := idutils.ValidateVersion(v); err != nil {
			return "", fmt.Errorf("version file contains an invalid version: %v", err)
		}
		return v, nil
	}
	return fallbackVersion()
}

func fallbackVersion() (string, error) {
	// Fall back to a version generated from the InstalledAsset proto hash if the build is not
	// stamped with a label. This guarantees we always provide a valid IDVersion to the rest of the
	// codebase.
	ia, err := GenerateInstalledAsset("")
	if err != nil {
		return "", fmt.Errorf("could not generate the InstalledAsset proto: %v", err)
	}
	version, err := runtime.SideloadedVersion(ia)
	if err != nil {
		return "", fmt.Errorf("could not create version: %v", err)
	}
	return version, nil
}

var providedServices = []string{
	"google.longrunning.Operations",
	"intrinsic_proto.assets.v1.AssetInstances",
	"intrinsic_proto.assets.v1.AssetInstancesReader",
	"intrinsic_proto.assets.v1.InstalledAssets",
	"intrinsic_proto.assets.v1.InstalledAssetsReader",
	"intrinsic_proto.data.v1.DataAssets",
	"intrinsic_proto.data_logger.DataLogger",
	"intrinsic_proto.geometry.GeometryService",
	"intrinsic_proto.kvstore.KVStore",
	"intrinsic_proto.scene_object.v1.SceneObjectImport",
	"intrinsic_proto.world.ObjectWorldService",
}

func getMetadata(version string) (*mpb.Metadata, error) {
	providedInterfaces := make([]*mpb.Interface, 0, len(providedServices))
	for _, service := range providedServices {
		providedInterfaces = append(providedInterfaces, &mpb.Interface{
			Uri: interfaceutils.GRPCURIPrefix + service,
		})
	}

	id, err := idutils.IDProtoFromString(platform.RuntimeAssetID)
	if err != nil {
		return nil, err
	}
	return &mpb.Metadata{
		AssetType:   atypepb.AssetType_ASSET_TYPE_SERVICE,
		DisplayName: "Intrinsic Runtime",
		IdVersion: &idpb.IdVersion{
			Id:      id,
			Version: version,
		},
		Vendor: &vendorpb.Vendor{
			DisplayName: "Intrinsic",
		},
		Documentation: &documentationpb.Documentation{
			Description: "Intrinsic Runtime",
		},
		ReleaseNotes: "Intrinsic Runtime",
		Provides:     providedInterfaces,
	}, nil
}

// GenerateInstalledAsset generates the runtime InstalledAsset proto.
func GenerateInstalledAsset(version string) (*iapb.InstalledAsset, error) {
	serviceProtoPrefixes := make([]string, 0, len(providedServices))
	for _, service := range providedServices {
		serviceProtoPrefixes = append(serviceProtoPrefixes, fmt.Sprintf("/%s/", service))
	}

	metadata, err := getMetadata(version)
	if err != nil {
		return nil, err
	}
	return &iapb.InstalledAsset{
		Name:     platform.RuntimeAssetID,
		Metadata: metadata,
		AssetSpecificMetadata: &iapb.InstalledAsset_ServiceSpecificMetadata{
			ServiceSpecificMetadata: &iapb.InstalledAsset_ServiceMetadata{
				ServiceProtoPrefixes: serviceProtoPrefixes,
			},
		},
	}, nil
}

// GenerateAssetInstance generates the runtime AssetInstance proto.
func GenerateAssetInstance(version string) (*aipb.AssetInstance, error) {
	metadata, err := getMetadata(version)
	if err != nil {
		return nil, err
	}
	return &aipb.AssetInstance{
		Name:   platform.RuntimeInstanceName,
		Asset:  platform.RuntimeAssetID,
		Config: &icpb.InstanceConfig{},
		Details: &aipb.AssetInstance_Details{
			Service: &aipb.AssetInstance_Details_Service{
				GrpcConnection: &gcpb.GrpcConnection{
					Address: ingressAddress,
					Metadata: []*gcpb.GrpcConnection_Metadata{
						{
							Key:   assetInstanceHeader,
							Value: platform.RuntimeInstanceName,
						},
					},
				},
			},
		},
		Metadata: metadata,
	}, nil
}

// GenerateResourceInstance generates the runtime ResourceInstance proto.
func GenerateResourceInstance(version string) (*resourcepb.ResourceInstance, error) {
	typeID := fmt.Sprintf("%s.%s", platform.RuntimeAssetID, version)

	resourceData := make(map[string]*rhpb.ResourceHandle_ResourceData)
	for _, service := range providedServices {
		resourceData[service] = &rhpb.ResourceHandle_ResourceData{}
	}

	return &resourcepb.ResourceInstance{
		Name:          platform.RuntimeInstanceName,
		TypeId:        typeID,
		Configuration: &anypb.Any{},
		ResourceHandle: &rhpb.ResourceHandle{
			Name: platform.RuntimeInstanceName,
			ConnectionInfo: &rhpb.ResourceConnectionInfo{
				Target: &rhpb.ResourceConnectionInfo_Grpc{
					Grpc: &rhpb.ResourceGrpcConnectionInfo{
						Address:        ingressAddress,
						ServerInstance: platform.RuntimeInstanceName,
						Header:         assetInstanceHeader,
					},
				},
			},
			ResourceData: resourceData,
		},
	}, nil
}
