# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

package(
    default_visibility = ["//visibility:public"],
)

filegroup(
    name = "building_block",
    srcs = [
        "building_block_tray/building_block_tray.dae",
        "building_block_tray/building_block_tray.sdf",
        "building_block_tray/model.config",
        "long/building_block_long.dae",
        "long/building_block_long.sdf",
        "long/building_block_long.stl",
        "long/model.config",
        "original/building_block.dae",
        "original/building_block.sdf",
        "original/building_block.stl",
        "original/model.config",
        "textured/building_block.dae",
        "textured/building_block.mtl",
        "textured/building_block.obj",
        "textured/building_block.sdf",
        "textured/building_block_blank.png",
        "textured/building_block_hinterst90deg.mtl",
        "textured/building_block_hinterst90deg.obj",
        "textured/building_block_intrinsic.png",
        "textured/building_block_jenga.png",
        "textured/model.config",
    ],
)
