// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef INTRINSIC_MOTION_PLANNING_PATH_PLANNING_PLANNERS_RRT_CONNECT_H_
#define INTRINSIC_MOTION_PLANNING_PATH_PLANNING_PLANNERS_RRT_CONNECT_H_

#include <memory>

#include "absl/status/statusor.h"
#include "intrinsic/eigenmath/types.h"
#include "intrinsic/motion_planning/path_planning/data_structures/path_planner_graph.h"
#include "intrinsic/motion_planning/path_planning/data_structures/state_sampler.h"
#include "intrinsic/motion_planning/path_planning/path_planner_definitions.h"
#include "intrinsic/motion_planning/path_planning/planners/rrt_configs.pb.h"

namespace intrinsic {
// Runs RRT-connect with a few function arguments to configure parts of the
// process. This allows enough flexibility to use different heuristics.
//
// The configurable functions are used as follows:
//   * validator: used to check whether points and edges are valid to use in the
//     tree built by rrt. Typically this is a collision check for the point/edge
//     but could also be bundled with other checks to change the space of valid
//     edges.
//   * get_config_fn: used in conjuction with scoring_fn to generate the next
//     point to expand to. Each iteration this function is used to generate
//     candidates, which are then scored and of which the top scoring one is
//     returned. The number of candidates created can be set in the passed
//     `config`. It is also assumed that the vertices being generated by this
//     function are valid for scoring though they will be checked for validity
//     against before being added to a tree.
//   * scoring_fn: Function which scores a vertex in terms of its potential as
//     the next point to expand the current tree to. The function has a
//     considerable number of arguments, but conceptually represents the full
//     state of the planner at the time of the call. Be aware that this function
//     is called on every candidate generated and that thus may end up being a
//     performance bottleneck. In particular, the GetNearestNeighbor call
//     supported by intrinsic::manipulation::RRT is LINEAR in the size of the
//     tree and can make the scoring function much slower as the trees get
//     larger.
//
// We currently expose some of the components of the blue path planning code.
// Later this is will be merged/extracted to have a cleaner interface.
absl::StatusOr<PointPath> PlanBidirectionalRrtConnect(
    const eigenmath::VectorXd& start, const eigenmath::VectorXd& goal,
    const proto::RrtConnectConfig& config,
    const PointValidator& point_validator, const EdgeValidator& edge_validator,
    std::unique_ptr<StateSampler> state_sampler,
    const ConstraintManifoldProjector& projector,
    PathPlannerGraph* graph = nullptr);

}  // namespace intrinsic

#endif  // INTRINSIC_MOTION_PLANNING_PATH_PLANNING_PLANNERS_RRT_CONNECT_H_
