// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.motion_planning;

import "intrinsic/icon/proto/joint_space.proto";
import "intrinsic/math/proto/pose.proto";
import "intrinsic/motion_planning/path_planning/path_segment.proto";
import "intrinsic/motion_planning/proto/v1/motion_specification.proto";
import "intrinsic/motion_planning/proto/v1/robot_specification.proto";

option go_package = "intrinsic_motion_planning/intrinsic/motion_planning/service/nonvolatile_cache/motion_planner_nonvolatile_cache_go_proto";

// The key type used for caching results from
// MotionPlannerService::PlanTrajectory to a nonvolatile storage.
message MotionPlannerNonvolatileCacheKey {
  message PosesOfTransformNodes {
    map<string, intrinsic_proto.Pose> poses_of_transform_nodes = 1;
  }

  // The MotionSpecification from the planning request.
  intrinsic_proto.motion_planning.v1.MotionSpecification motion_specification =
      1;

  // The RobotSpecification from the planning request but without the
  // `start_configuration`.
  intrinsic_proto.motion_planning.v1.RobotSpecification robot_specification = 2;

  // References and poses in root frame of all transform nodes referred in each
  // motion segment.
  repeated PosesOfTransformNodes poses_of_all_related_transform_nodes = 3;

  // The starting robot configuration in the request.
  intrinsic_proto.icon.JointVec starting_robot_configuration = 4;

  // Motion ID used to load the cache entry. Not used for comparison against
  // other cache keys and not used for saving caches. Used for
  // informational-purposes only.
  string uuid = 5;

  // `MotionPlannerService` (MPS) Asset major version. Variations of MPS Asset
  // minor version may still result in cache hits as long as both the major
  // version (`mps_asset_major_version`) and the `motion_planning_proto_version`
  // are the same.
  string mps_asset_major_version = 6;

  // Motion Planning proto version.
  string motion_planning_proto_version = 7;
}

// The value type used for caching results from
// MotionPlannerService::PlanTrajectory to a nonvolatile storage.
message MotionPlannerNonvolatileCacheValue {
  // The planned trajectory.
  intrinsic_proto.icon.JointTrajectoryPVA trajectory = 1;
  // The path segments used to generate the planned trajectory.
  repeated intrinsic_proto.motion_planning.PathSegment path_segments = 2;
}

// The entry (key+value) type used for caching results from
// MotionPlannerService::PlanTrajectory to a nonvolatile storage.
message MotionPlannerNonvolatileCacheEntry {
  // The key used to save the planning result.
  MotionPlannerNonvolatileCacheKey key = 1;
  // The planning result to save.
  MotionPlannerNonvolatileCacheValue value = 2;
}
