# proto-file: intrinsic/scene/proto/v1/scene_object_updates.proto
# proto-message: intrinsic_proto.scene_object.v1.SceneObjectUpdates

# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


updates {
  update_joints {
    joint_positions {
      key: "joint_a1"
      value: 0.0
    }
    joint_positions {
      key: "joint_a2"
      value: -1.5707963267948966
    }
    joint_positions {
      key: "joint_a3"
      value: 2.146754979999999
    }
    joint_positions {
      key: "joint_a4"
      value: 0.0
    }
    joint_positions {
      key: "joint_a5"
      value: 1.5707963267948966
    }
    joint_positions {
      key: "joint_a6"
      value: 0.0
    }
    joint_system_limits {
      key: "joint_a1"
      value {
        min_position: -3.22886
        max_position: 3.22886
        max_velocity: 3.49066
        max_acceleration: 8.50
        max_jerk: 1287.90
        max_effort: 200  # Effort limits are not tuned to this robot.
      }
    }
    joint_system_limits {
      key: "joint_a2"
      value {
        min_position: -3.22886
        max_position: 1.13446
        max_velocity: 3.05433
        max_acceleration: 2.22
        max_jerk: 330.55
        max_effort: 200  # Effort limits are not tuned to this robot.
      }
    }
    joint_system_limits {
      key: "joint_a3"
      value {
        min_position: -2.40855
        max_position: 3.05433
        max_velocity: 3.31613
        max_acceleration: 9.09
        max_jerk: 1377.13
        max_effort: 200  # Effort limits are not tuned to this robot.
      }
    }
    joint_system_limits {
      key: "joint_a4"
      value {
        min_position: -6.10865
        max_position: 6.10865
        max_velocity: 7.50492
        max_acceleration: 71.27
        max_jerk: 10799.21
        max_effort: 200  # Effort limits are not tuned to this robot.
      }
    }
    joint_system_limits {
      key: "joint_a5"
      value {
        min_position: -2.26893
        max_position: 2.26893
        max_velocity: 7.50492
        max_acceleration: 68.17
        max_jerk: 10328.72
        max_effort: 200  # Effort limits are not tuned to this robot.
      }
    }
    joint_system_limits {
      key: "joint_a6"
      value {
        min_position: -6.10865
        max_position: 6.10865
        max_velocity: 10.9956
        max_acceleration: 111.44
        max_jerk: 16884.93
        max_effort: 200  # Effort limits are not tuned to this robot.
      }
    }

    # Application position limits are 0.1 rad offset from the system limits.
    # Velocity, acceleration and jerk are 90% of system limits.
    joint_application_limits {
      key: "joint_a1"
      value {
        min_position: -3.12886
        max_position: 3.12886
        max_velocity: 3.14159
        max_acceleration: 7.65
        max_jerk: 1159.11
        max_effort: 180  # Effort limits are not tuned to this robot.
      }
    }
    joint_application_limits {
      key: "joint_a2"
      value {
        min_position: -3.12886
        max_position: 1.03446
        max_velocity: 2.7489
        max_acceleration: 2.00
        max_jerk: 297.49
        max_effort: 180  # Effort limits are not tuned to this robot.
      }
    }
    joint_application_limits {
      key: "joint_a3"
      value {
        min_position: -2.30855
        max_position: 2.95433
        max_velocity: 2.98452
        max_acceleration: 8.18
        max_jerk: 1239.42
        max_effort: 180  # Effort limits are not tuned to this robot.
      }
    }
    joint_application_limits {
      key: "joint_a4"
      value {
        min_position: -6.00865
        max_position: 6.00865
        max_velocity: 6.75443
        max_acceleration: 64.14
        max_jerk: 9719.29
        max_effort: 180  # Effort limits are not tuned to this robot.
      }
    }
    joint_application_limits {
      key: "joint_a5"
      value {
        min_position: -2.16893
        max_position: 2.16893
        max_velocity: 6.75443
        max_acceleration: 61.35
        max_jerk: 9295.85
        max_effort: 180  # Effort limits are not tuned to this robot.
      }
    }
    joint_application_limits {
      key: "joint_a6"
      value {
        min_position: -6.00865
        max_position: 6.00865
        max_velocity: 9.89604
        max_acceleration: 100.29
        max_jerk: 15196.43
        max_effort: 180  # Effort limits are not tuned to this robot.
      }
    }
  }
}
