// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package operations contains helpers to work with long-running operations.
package operations

import (
	"context"
	"fmt"
	"sync"
	"time"

	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"

	lropb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	anypb "google.golang.org/protobuf/types/known/anypb"
)

// Allows changing in tests.
var timeNow = time.Now

// Operation wraps an operation and exposes added functionality like thread-safe modifications and
// cancellation through a friendly API.
type Operation struct {
	mu sync.Mutex
	o  *lropb.Operation
	// Allows usage of [Operation.Cancel] if set.
	cancel context.CancelCauseFunc

	createTime time.Time
	// A channel that is closed to signal that the operation is done.
	doneChan chan struct{}
}

// New creates an [Operation] wrapping the given proto. The provided operation proto is cloned
// before wrapping. Changes to the original proto will not propagate.
func New(op *lropb.Operation) *Operation {
	doneChan := make(chan struct{})
	if op.GetDone() {
		close(doneChan)
	}
	return &Operation{
		o:          proto.Clone(op).(*lropb.Operation),
		createTime: timeNow(),
		doneChan:   doneChan,
	}
}

// NewWithPrefix creates a new Operation with a name generated by joining the provided prefix
// with a UUID as "{prefix}/{UUID}".
func NewWithPrefix(prefix string) *Operation {
	return New(&lropb.Operation{
		Name: fmt.Sprintf("%s/%s", prefix, uuidNew()),
	})
}

// Done returns whether the operation is marked as done.
func (o *Operation) Done() bool {
	o.mu.Lock()
	defer o.mu.Unlock()
	return o.o.GetDone()
}

// Name returns the name of the operation.
func (o *Operation) Name() string {
	o.mu.Lock()
	defer o.mu.Unlock()
	return o.o.GetName()
}

// Proto returns a *clone* of the underlying operation proto.
func (o *Operation) Proto() *lropb.Operation {
	if o == nil {
		return nil
	}
	o.mu.Lock()
	defer o.mu.Unlock()
	return proto.Clone(o.o).(*lropb.Operation)
}

// CreateTime returns the UTC time at which the operation was created.
func (o *Operation) CreateTime() time.Time {
	return o.createTime.UTC()
}

// Cancel cancels the operation was added to a [Queue] through [Queue.Enqueue]. No-op if the
// operation is not enqueued, already complete or already canceled.
func (o *Operation) Cancel(cause error) {
	o.mu.Lock()
	defer o.mu.Unlock()
	if o.cancel != nil {
		o.cancel(cause)
		o.cancel = nil
	}
}

// Sets the cancel function for the operation. Prefer using this over setting cancel directly to be
// concurrency safe. `cancel` is ignored if the operation is already done.
func (o *Operation) setCancel(cancel context.CancelCauseFunc) {
	o.mu.Lock()
	defer o.mu.Unlock()
	if !o.o.GetDone() {
		o.cancel = cancel
	}
}

// Metadata retrieves the metadata from the operation and unpacks it to the provided metadata
// message. This allows incrementally updating metadata. If the provided metadata message has a
// wrong type, an error is returned.
func (o *Operation) Metadata(msg proto.Message) error {
	o.mu.Lock()
	defer o.mu.Unlock()
	return o.o.GetMetadata().UnmarshalTo(msg)
}

// SetMetadata sets the metadata of the operation in place.  An error is
// returned if the message cannot be packed into an Any message.
func (o *Operation) SetMetadata(metadata proto.Message) error {
	o.mu.Lock()
	defer o.mu.Unlock()
	anyMessage, err := anypb.New(metadata)
	if err != nil {
		return err
	}
	o.o.Metadata = anyMessage
	return nil
}

// ClearMetadata clears the metadata of the operation in place.
func (o *Operation) ClearMetadata() {
	o.mu.Lock()
	defer o.mu.Unlock()
	o.o.Metadata = nil
}

// SetResponse sets the result of the operation to the provided response.
func (o *Operation) SetResponse(response proto.Message) error {
	o.mu.Lock()
	defer o.mu.Unlock()
	anyMessage, err := anypb.New(response)
	if err != nil {
		return err
	}
	o.o.Result = &lropb.Operation_Response{Response: anyMessage}
	if !o.o.GetDone() {
		o.o.Done = true
		o.cancel = nil
		close(o.doneChan)
	}
	return nil
}

// SetError sets the result of the operation to the given error. The operation will be marked as
// done automatically. The status code in the error is used if present. Otherwise the status code is
// set to UNKNOWN.
func (o *Operation) SetError(err error) {
	o.mu.Lock()
	defer o.mu.Unlock()
	o.o.Result = &lropb.Operation_Error{
		Error: status.Convert(err).Proto(),
	}
	if !o.o.GetDone() {
		o.o.Done = true
		o.cancel = nil
		close(o.doneChan)
	}
}

// doneChannel is a helper to get a copy of the channel to wait upon so that
// the functions waiting don't hold the lock indefinitely.
func (o *Operation) doneChannel() <-chan struct{} {
	o.mu.Lock()
	defer o.mu.Unlock()
	return o.doneChan
}

// Wait will block until the operation is done.
func (o *Operation) Wait() {
	<-o.doneChannel()
}

// WaitFor will block until the operation is done or the timeout is reached.
func (o *Operation) WaitFor(timeout time.Duration) {
	select {
	case <-o.doneChannel():
	case <-time.After(timeout):
	}
}
