# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

package(
    default_visibility = ["//visibility:public"],
)

filegroup(
    name = "bluebird",
    srcs = [
        "calibration_fixture/charuco_holder.glb",
        "calibration_fixture/charuco_holder.sdf",
        "calibration_fixture/model.config",
        "dice/dice.sdf",
        "dice/dice.stl",
        "dice/model.config",
        "nest/collision_geometry.stl",
        "nest/collision_geometry_simple.stl",
        "nest/model.config",
        "nest/nest.sdf",
        "nest/visual_geometry.dae",
        "open_box/model.config",
        "open_box/open_box.sdf",
        "open_box/open_box.stl",
        "open_box/open_box_collision.stl",
        "part_bin/model.config",
        "part_bin/part_bin.dae",
        "part_bin/part_bin.sdf",
        "red_bin/model.config",
        "red_bin/red_bin.dae",
        "red_bin/red_bin.sdf",
        "wood_plate/model.config",
        "wood_plate/wood_plate.glb",
        "wood_plate/wood_plate.sdf",
        "workcell/model.config",
        "workcell/workcell.dae",
        "workcell/workcell.sdf",
        "workcell/workcell.stl",
        "workcell/workcell_collision.stl",
        "workcell/workcell_collision_no_table.stl",
    ],
)
