; Copyright 2026 Intrinsic Innovation LLC
;
; Licensed under the Apache License, Version 2.0 (the "License");
; you may not use this file except in compliance with the License.
; You may obtain a copy of the License at
;
;     https://www.apache.org/licenses/LICENSE-2.0
;
; Unless required by applicable law or agreed to in writing, software
; distributed under the License is distributed on an "AS IS" BASIS,
; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
; See the License for the specific language governing permissions and
; limitations under the License.

; Definitions for the Executive state

; Requires:
; - protobuf: create protos
; - plan.clp: plan template
; - tracing.clp: status codes and functions handling spans

; --------------------------------- TEMPLATES ---------------------------------

(deftemplate executive-state
  (slot state (type SYMBOL) (allowed-values UNSPECIFIED CREATING ACTIVE))

  ; If non-empty, top-level context IDs for a session to associate with all
  ; log requests.
  (slot session-log-id (type INTEGER))
)

(deftemplate executive-force-cancel
  (slot message (type STRING) (default ?NONE))
)

; ---------------------------- FORWARD DECLARATIONS ----------------------------

; defined in behavior_tree.clp
(deffunction behavior-tree-get-log-id (?tree-id))
(deffunction behavior-tree-cancel (?tree-id))

; --------------------------------- FUNCTIONS ---------------------------------

; Creates a state context proto.
; Returns a log Context proto with the session ID set, and if an operation name
; is specified also the process tree's log id.
;
; Args:
;   ?operation-name: Name of the operation this context pertains to. Can be
;                    empty if not specific to an operation.
;
; Returns:
;   Proto id of a newly created LogContxt proto. The caller owns the proto.
(deffunction executive-state-create-context-proto (?operation-name)
  (bind ?context-proto 0)
  (do-for-fact ((?es executive-state)) TRUE
    (bind ?context-proto (log-context-create ?es:session-log-id 0 0 0
                                             ?operation-name))
  )
  (if (= ?context-proto 0) then (return 0))

  (do-for-fact ((?op operation-envelope)) (eq ?op:name ?operation-name)
    (pb-set-field ?context-proto "executive_plan_id"
                  (behavior-tree-get-log-id ?op:operation-tree-id))
  )

  (return ?context-proto)
)

; ----------------------------------- RULES -----------------------------------

(defrule executive-state-active
  "Switch from CREATING to ACTIVE once we have a session log ID"
  ; Make sure to run as last of the initializer rules
  (declare (salience ?*SALIENCE-LAST*))
  ; Session Log IDs generated by log-create-session in logging.clp
  ?sf <- (executive-state (state CREATING) (session-log-id ~0))
 =>
  (modify ?sf (state ACTIVE))
)

(defrule executive-state-force-cancel
  "Force-Cancels all running trees."
  ; Set highest salience to enable emergency cancellation on run-away processes.
  (declare (salience ?*SALIENCE-FIRST*))
  ?cf <- (executive-force-cancel (message ?message))
 =>
  (printout error
    "************************* FORCED CANCELLATION *************************"
    crlf ?message crlf
    "***********************************************************************"
    crlf)
  (retract ?cf)
  (assert (error (type RECOVERABLE)
                 (name EXECUTIVE-STATE-FORCE-CANCEL)
                 (message ?message)))

  (do-for-fact ((?op operation-envelope)) TRUE
    (printout error (str-cat "Canceling operation " ?op:name
                             " in state " ?op:state) crlf)
    (if (not (behavior-tree-cancel ?op:operation-tree-id))
      then
        (printout error "Failed to cancel process tree." crlf)
      else
        (modify ?op (state CANCELING))
    )
  )
)

(defrule executive-state-fail-on-fatal-error
  "Handle FATAL errors."
  (error (type FATAL) (message ?message))
 =>
  (printout error "Stopping executive as FATAL errors occurred." crlf)
  (assert (executive-force-cancel
            (message (str-cat "FATAL errors have been found: " ?message))))
)
