// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package webrtc implements WebRTC signaling and data channel pub/sub transport for real-time client communication.
package webrtc

import (
	"fmt"

	"intrinsic/httpjson/proto/v1alpha/signalling_go_proto"

	pion "github.com/pion/webrtc/v4"
)

// ToPionSessionDescription converts the proto description to Pion's format.
func ToPionSessionDescription(pbDesc *signalling_go_proto.RtcSessionDescription) (pion.SessionDescription, error) {
	if pbDesc == nil {
		return pion.SessionDescription{}, fmt.Errorf("session description proto is nil")
	}
	var sdpType pion.SDPType
	switch pbDesc.Type {
	case signalling_go_proto.RtcSessionDescription_offer:
		sdpType = pion.SDPTypeOffer
	case signalling_go_proto.RtcSessionDescription_pranswer:
		sdpType = pion.SDPTypePranswer
	case signalling_go_proto.RtcSessionDescription_answer:
		sdpType = pion.SDPTypeAnswer
	case signalling_go_proto.RtcSessionDescription_rollback:
		sdpType = pion.SDPTypeRollback
	default:
		return pion.SessionDescription{}, fmt.Errorf("unsupported or unspecified SDP type: %v", pbDesc.Type)
	}
	return pion.SessionDescription{
		Type: sdpType,
		SDP:  pbDesc.Sdp,
	}, nil
}

// ToProtoSessionDescription converts Pion's description back into the protobuf format.
func ToProtoSessionDescription(pionDesc pion.SessionDescription) (*signalling_go_proto.RtcSessionDescription, error) {
	var pbType signalling_go_proto.RtcSessionDescription_SdpType
	switch pionDesc.Type {
	case pion.SDPTypeOffer:
		pbType = signalling_go_proto.RtcSessionDescription_offer
	case pion.SDPTypePranswer:
		pbType = signalling_go_proto.RtcSessionDescription_pranswer
	case pion.SDPTypeAnswer:
		pbType = signalling_go_proto.RtcSessionDescription_answer
	case pion.SDPTypeRollback:
		pbType = signalling_go_proto.RtcSessionDescription_rollback
	default:
		return nil, fmt.Errorf("unsupported Pion SDP type: %s", pionDesc.Type.String())
	}
	return &signalling_go_proto.RtcSessionDescription{
		Type: pbType,
		Sdp:  pionDesc.SDP,
	}, nil
}

// ToPionIceCandidate maps the candidate fields to Pion's format.
func ToPionIceCandidate(pbCand *signalling_go_proto.RtcIceCandidate) (pion.ICECandidateInit, error) {
	if pbCand == nil {
		return pion.ICECandidateInit{}, fmt.Errorf("ice candidate proto is nil")
	}
	var sdpMLineIndex *uint16
	if pbCand.SdpMLineIndex != nil {
		val := *pbCand.SdpMLineIndex
		if val < 0 || val > 65535 {
			return pion.ICECandidateInit{}, fmt.Errorf("invalid sdp_m_line_index value: %d", val)
		}
		uval := uint16(val)
		sdpMLineIndex = &uval
	}
	return pion.ICECandidateInit{
		Candidate:        pbCand.Candidate,
		SDPMid:           pbCand.SdpMid,
		SDPMLineIndex:    sdpMLineIndex,
		UsernameFragment: pbCand.UsernameFragment,
	}, nil
}

// ToProtoIceCandidate formats local ICE candidates generated by Pion for serialization.
func ToProtoIceCandidate(pionCand pion.ICECandidate) (*signalling_go_proto.RtcIceCandidate, error) {
	init := pionCand.ToJSON()
	var sdpMLineIndex *int32
	if init.SDPMLineIndex != nil {
		val := int32(*init.SDPMLineIndex)
		sdpMLineIndex = &val
	}
	return &signalling_go_proto.RtcIceCandidate{
		Candidate:        init.Candidate,
		SdpMid:           init.SDPMid,
		SdpMLineIndex:    sdpMLineIndex,
		UsernameFragment: init.UsernameFragment,
	}, nil
}
