// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package webrtc implements WebRTC signaling and data channel pub/sub transport for real-time client communication.
package webrtc

import (
	"fmt"
	"log/slog"
	"strings"

	pion "github.com/pion/webrtc/v4"
)

// SignalHandlingListener defines callbacks for events generated by the SignalingHandler.
type SignalHandlingListener interface {
	OnLocalCandidate(candidate *pion.ICECandidate)
}

// SignalingHandler manages WebRTC SDP offer/answer exchanges and ICE candidate trickling.
type SignalingHandler struct {
	pc       *pion.PeerConnection
	localIPs []string
}

// NewSignalingHandler creates and registers callbacks on a new SignalingHandler.
func NewSignalingHandler(pc *pion.PeerConnection, localIPs []string, listener SignalHandlingListener) *SignalingHandler {
	h := &SignalingHandler{
		pc:       pc,
		localIPs: localIPs,
	}
	h.registerCallbacks(listener)
	return h
}

func (h *SignalingHandler) registerCallbacks(listener SignalHandlingListener) {
	// Stream local ICE candidates to the remote peer as they are discovered so connection negotiation can begin before candidate gathering completes.
	h.pc.OnICECandidate(func(candidate *pion.ICECandidate) {
		if candidate == nil {
			slog.Info("Local ICE candidate gathering complete")
			return
		}
		rewritten := rewriteHostCandidateToLocalIPs(candidate, h.localIPs)
		for _, cand := range rewritten {
			listener.OnLocalCandidate(cand)
		}
	})
}

// OnRemoteSessionDescription handles SDP offers and answers received from the remote peer.
// If it receives an Offer, it returns the generated local Answer.
// If it receives an Answer, it sets the remote description and returns nil.
func (h *SignalingHandler) OnRemoteSessionDescription(desc pion.SessionDescription) (*pion.SessionDescription, error) {
	if desc.Type == pion.SDPTypeOffer {
		// Check that the SDP contains a m=application media line indicating a DataChannel is requested.
		if !strings.Contains(desc.SDP, "m=application") {
			return nil, fmt.Errorf("SDP offer must request a DataChannel (m=application)")
		}

		if err := h.pc.SetRemoteDescription(desc); err != nil {
			return nil, fmt.Errorf("SetRemoteDescription failed: %w", err)
		}

		answer, err := h.pc.CreateAnswer(nil)
		if err != nil {
			return nil, fmt.Errorf("CreateAnswer failed: %w", err)
		}

		if err := h.pc.SetLocalDescription(answer); err != nil {
			return nil, fmt.Errorf("SetLocalDescription failed: %w", err)
		}

		return &answer, nil

	} else if desc.Type == pion.SDPTypeAnswer {
		if err := h.pc.SetRemoteDescription(desc); err != nil {
			return nil, fmt.Errorf("SetRemoteDescription (answer) failed: %w", err)
		}
		return nil, nil
	} else {
		return nil, fmt.Errorf("unsupported session description type: %v", desc.Type)
	}
}

// OnRemoteIceCandidate handles ICE candidates received from the remote peer.
func (h *SignalingHandler) OnRemoteIceCandidate(candidate pion.ICECandidateInit) error {
	if err := h.pc.AddICECandidate(candidate); err != nil {
		return fmt.Errorf("failed to add remote ICE candidate to PeerConnection: %w", err)
	}
	return nil
}
