// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "intrinsic/icon/hardware_modules/universal_robots/ur_error_codes.h"

#include <cstddef>

#include "absl/base/no_destructor.h"
#include "absl/container/flat_hash_map.h"
#include "absl/strings/string_view.h"

namespace intrinsic::icon {

absl::flat_hash_map<size_t, absl::string_view> CreateUrErrorCodeMap() {
  // Taken from
  // https://www.universal-robots.com/manuals/EN/HTML/SW5_21/Content/Landingpages/Web/ErrorCodes.htm.
  // Some messages with replacements (`{xxx}`) have been adjusted.
  // Look for "// Adjusted" comments below when updating the error codes.
  absl::flat_hash_map<size_t, absl::string_view> map = {
      {0, "No error"},
      {1, "Outbuffer overflow"},
      {2, "Inbuffer overflow"},
      {3, "Processor overloaded"},
      {4, "Communication issue"},
      {5, "Heavy processor load warning"},
      {10, "Controller communication issue"},
      {11, "Bad CRC"},
      {12, "Unknown message error"},
      {14, "Debug message"},
      {17, "Communication error between Safety Control Board and Motherboard"},
      {25, "Motor Encoder index missing"},
      {26, "Motor Encoder index drift detected"},
      {27,
       "Calibration data is invalid or does not exist, selftest is needed!"},
      {29, "Online Calibration data checksum failed"},
      {30, "Master received data from too many joints"},
      {31, "Caught wrong message (not from master)"},
      {32, "Flash write verify failed"},
      {33, "Calibration flash checksum failed"},
      {34, "Program flash checksum failed"},
      {35, "Joint ID is undefined"},
      {36, "Illegal bootloader command"},
      {37, "Inbuffer parse error"},
      {38, "Online RAM test failed"},
      {39, "Logic and Temporal Monitoring Fault"},
      {40, "AD-Converter hit high limit joint"},
      {41, "RC Oscillator Trim register hit high limit"},
      {42, "RC Oscillator Trim register hit low limit"},
      {43, "Change in invariant memory detected"},
      {44, "CRC check failure on primary bus"},
      {45, "AD-Converter error"},
      {46, "Loose gearbox or bad encoder mounting"},
      {47, "AD-Converter hit low limit"},
      {49, "RS485 receive warning"},
      {50, "Robot powerup issue"},
      {51, "CRC check failure on secondary bus"},
      {53, "IO overcurrent detected"},
      {55, "Safety system error"},
      {56, "Overvoltage shutdown"},
      {57, "Brake release failure"},
      {58, "Motor encoder not calibrated"},
      {59, "Overcurrent shutdown"},
      {60, "Energy surplus shutdown"},
      {61, "Idle power consumption to high"},
      {62, "Thermal issue"},
      {63, "Motor test failed in step {unsigned}."},
      {65, "PSU voltage to high"},
      {68, "SPI error"},
      {70, "Close to gearbox shear limit"},
      {71, "Startup check error"},
      {72, "Power Supply Unit failure"},
      {73, "Brake test failed during selftest, check brakepin"},
      {74, "Joint encoder warning"},
      {75, "Joint encoder error"},
      {76, "Joint encoder communication CRC issue"},
      {77, "Sudden position change detected on the joint-encoder"},
      {78, "Large sudden position change detected on the joint-encoder"},
      {85, "Motor encoder error"},
      {100, "Robot changed mode"},
      {101, "Real Robot Connected"},
      {102, "Real Robot not connected - Simulating Robot"},
      {103, "Communication issue"},
      {104, "Error=Empty command sent to robot"},
      {111, "Something is pulling the robot"},
      {115, "Unknown robot type"},
      {116, "Realtime part warning"},
      {117, "Restart SCB failed"},
      {150, "Position close to joint limits"},
      {151, "Tool orientation close to limits"},
      {152, "Position close to safety plane limits"},
      {153, "Position deviates from path"},
      {154, "Position in singularity"},
      {155, "Robot cannot maintain its position, check if payload is correct"},
      {156,
       "Wrong payload or mounting detected, or something is pushing the robot "
       "when entering Freedrive mode"},
      {157, "Collision detected by joint"},
      {158, "Collision detected by joint"},
      {159, "Position deviates from path"},
      {160,
       "The robot was powered off last time due to a joint position "
       "disagreement"},
      {161,
       "Large movement of the robot detected while it was powered off. The "
       "joints were moved while it was powered off, or the encoders do not "
       "function"},
      {162,
       "The protective stop was likely caused by incorrectly specified payload "
       "mass and/or center of gravity."},
      {171, "Issue with blends"},
      {172, "Illegal control mode"},
      {173, "Robot motion causes too high joint torques"},
      {174, "Robot motion causes too high jump in joint torques"},
      {184, "Joint self test not received by controller"},
      {187, "Temperature sensor test failed"},
      {190, "Joint failed during selftest"},
      {191, "Safety system violation"},
      {192, "Safety system fault"},
      {193, "One of the nodes is in fault mode"},
      {194, "One of the nodes is not booted or not present"},
      {195, "Conveyor speed too high"},
      {196, "MoveP speed too high"},
      {197, "Blend overlap warning"},
      {200, "Safety Control Board hardware error"},
      {201, "Setup of Safety Control Board failed"},
      {202, "SCE configuration was illegal, after applying tolerances"},
      {203,
       "PolyScope detected a mismatch between the shown and (to be) applied "
       "safety parameters"},
      {204, "Path sanity check failed"},
      {205, "Target speed does not match target position"},
      {206, "Sanity check failed"},
      {207, "Fieldbus input disconnected"},
      {208, "Debug Assertion failed"},
      {209, "A protective stop was triggered (for test purposes only)"},
      {210,
       "Socket is read-only when the robot is in local (Teach pendant) "
       "control"},
      {211, "Operational mode changed"},
      {212, "Name conflict in loaded program"},
      {213,
       "No Kinematic Calibration found (calibration.conf file is either "
       "corrupt or missing)"},
      {214, "Kinematic Calibration for the robot does not match the joint(s)"},
      {215, "Kinematic Calibration does not match the robot"},
      {216, "The offset of the joint has changed"},
      {217,
       "White space detected at the beginning of a string token at line "
       "{unsigned}"},
      {218, "A thread used a lot of time"},
      {219, "Change in offset is too high"},
      {220, "Kinematic Calibration"},
      {221, "GUI Communication"},
      // Adjusted
      {257,
       "An unexpected message was received (See teach pendant for header "
       "value)"},
      // Adjusted
      {258,
       "Message contains invalid payload (See teach pendant for data value)"},
      {259, "Filesystem-related issue"},
      {260, "Brake Release - old procedure"},
      {261, "Temperature Sensor"},
      {262, "Communication"},
      {263, "Motor Encoder"},
      {264, "Task Manager"},
      {265, "Joint Encoder"},
      {266, "Self-test"},
      {267, "Bootloader error"},
      {268, "Special Command"},
      {269, "Transceiver - deprecated"},
      {270, "Self-test SYNC"},
      {271, "Low level real-time thread"},
      {272, "Missing calibration"},
      {273, "Cross monitoring"},
      {274, "Control box fan error"},
      {275, "Brake Pin"},
      {276, "Uart"},
      {277, "Memory"},
      {278, "Servo"},
      {279, "Flash"},
      {280, "Real-time error"},
      {281, "Robot State Machine"},
      {282, "Systick"},
      {283, "Safety system"},
      {284, "Brake Release"},
      {285, "Joint Keep-Alive System"},
      {286, "Motor Controller"},
      {287, "Saved files"},
      {288, "IO control"},
      {289, "Tool Connector"},
      {290, "I2C"},
      {291, "EEPROM"},
      {292, "Online RAM test"},
      {293, "Exception"},
      {294, "ADC"},
      {295, "PCB"},
      {296, "Start up check"},
      {297, "Joint validation"},
      {298, "Hand protection"},
      {299, "Tool communication"},
      {300, "Safety message"},
      {301, "Safety message monitor"},
      {302, "Tool Configuration"},
      {303, "System status"},
      {304, "Self monitoring"},
      {305, "Robot Power Control"},
      {306, "Joint"},
      {307, "Data B: {data}"},
      {308, "Data A: {data}"},
      {309, "Keep-Alive System"},
      {311, "Delay Callback"},
      {312, "Data validation"},
      {313, "App version"},
      {314, "SPI IO"},
      {315, "Watchdog"},
      {316, "MCU"},
      {317, "Failure injection"},
      {318, "Stack monitor"},
      {319, "Filesys Diagnostic Tool"},
      {320, "REDnet BLVDS"},
      {321, "REDnet RS485"},
      {322, "Switch"},
      {323, "SCB Endpoint"},
      {324, "TP UART"},
      {325, "SPI uA"},
      {326, "SPI uB"},
      {327, "PCIe"},
      {328, "Transceiver miscellaneous"},
      {329, "AXI STREAM"},
      {330, "IMMI IO"},
      {331, "Friction model"},
      {332, "Servo configuration"},
      {333, "File message"},
      {334,
       "Robot deviated from constrained axes while in Constrained Freedrive."},
      {336, "Hardware configuration manager"},
      {337, "Control parameters"},
      {338, "PROFIsafe"},
      {339, "Cross communication"},
      {340, "Energy Monitoring"},
      {400, "Elbow position close to safety plane limits"},
      {401, "Exceeding user safety settings for stopping time"},
      {402, "Exceeding user safety settings for stopping distance"},
      {403, "Danger of clamping between the Robot's lower arm and tool"},
      {404, "Unexpected behavior"},
      {450, "Force-Torque sensor"},
      {499, "Motorencoder calibration"},
      {500, "Self-test step"},
      {501, "PC Selftest message"},
      {502, "Additional information"},
      {503, "Limit Violation - ADC calibration"},
      {504, "Limit Violation - Commutation offset calibration"},
      {505, "Limit Violation - Brake test"},
      {506, "Limit Violation - Zero torque offset calibration"},
      {507, "Limit Violation - Joint Calibration"},
      {508, "Deviation - Joint Calibration"},
      {509, "Limit Violation - Cogging calibration"},
      {510, "Limit Violation - Temperature"},
      {511, "Limit Violation - Joint encoder calibration"},
      {512, "Limit Violation - Motor encoder calibration"},
      {513, "Motor encoder statistics"},
      {514, "Limit Violation - RLS Encoder Signal Quality"},
      {515, "Limit Violation - Motor Parameters"},
      {516, "Selftest disagreement"},
      {517, "Limit Violation - Vibration Measurement"},
      {518, "Joint Selftest Data Message"},
      {519, "Limit Violation - Hardware Information"},
      {520, "Limit Violation - Commutation Offset Correction"},
      {522, "Limit Violation - Kinematic Error Calibration"},
      {710, "ROM Test"},
      {720, "LVD (low voltage detection)"},
      {740, "Hardware monitoring"},
      // Adjusted
      {900, "Debug message data (See teach pendant for data value)"},
  };
  return map;
}

const absl::flat_hash_map<size_t, absl::string_view>&
UrErrorCodeToStringMapSingleton() {
  static absl::NoDestructor<absl::flat_hash_map<size_t, absl::string_view>>
      static_map(CreateUrErrorCodeMap());
  return *static_map;
}

}  // namespace intrinsic::icon
