// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.scene.cad;

import "intrinsic/scene/proto/v1/imported_scene.proto";

option go_package = "intrinsic/scene/cad/cad_import_service_go_proto";

// Service for importing CAD data.
service CADImportService {
  // Requests a new CAD import and expects a stream of response containing one
  // world fragment. The streaming interface is an artifact of an older version
  // of this interface.
  rpc ImportCAD(CADImportRequest) returns (stream CADImportResponse);
}

message CADImportRequest {
  CADImportFileData import_file_data = 4;

  CADImportConfig config = 3;
  // Distinguish between importing to world fragment and importing to scene
  // object composed scenes.
  CADImportTargetFormat target_format = 5;

  reserved 1, 2;
  reserved "import_resolution", "cad_file_data";
}

message CADImportConfig {
  ImportResolution import_resolution = 1;

  // Preferred imported scene structure. Only useful if CADImportTargetFormat is
  // IMPORTED_SCENE.
  intrinsic_proto.scene_object.v1.ImportStructure import_structure = 2;
}

enum CADImportTargetFormat {
  // Default value. This would be IMPORTED_SCENE.
  CAD_IMPORT_TARGET_FORMAT_UNSPECIFIED = 0;
  // CADImportResponse returns the oneof scene_result.
  IMPORTED_SCENE = 2;

  reserved 1;
  reserved "WORLD_FRAGMENT";
}

message ImportResolution {
  enum TesselationGranularity {
    UNKNOWN = 0;
    COARSE = 1;
    FINE = 2;
  }
  TesselationGranularity tesselation_granularity = 1;
}

// A stream of this response represents a world fragment. The streaming
// interface is an artifact of an older version of this interface.
message CADImportResponse {
  oneof scene_result {
    intrinsic_proto.scene_object.v1.ImportedScene imported_scene = 3;
  }
  reserved 1, 2;
  reserved "geometry_with_id", "world_fragment";
}

message CADImportFileData {
  string file_name = 1;
  bytes data = 2;
}
