# proto-file: intrinsic/assets/proto/status_spec.proto
# proto-message: intrinsic_proto.executive.StatusSpecs

# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


status_info: [
  {
    code: 12001
    title: "Invalid type URL for proto retrieval"
    recovery_instructions:
      "The proto registry requires type URLs starting with "
      "'type.intrinsic.ai/' and conforming to the Intrinsic URL "
      "specification."
  },
  {
    code: 12100
    title: "Unknown asset in type URL"
    recovery_instructions:
      "The asset you tried to get the file descriptor for does not exist. "
      "Add it to the solution."
  },
  {
    code: 12101
    title: "Unknown well-known type in type URL"
    recovery_instructions:
      "The proto registry does not recognize this message as a well-known "
      "type. Use an asset type URL if this is a custom message."
  },
  # Codes 13000-14060 are reserved / have been used before. Only 13003 is still in use.
  {
    code: 13003
    title: "Assignability check skipped"
  }
]
