# proto-file: intrinsic/skills/proto/skill_manifest.proto
# proto-message: intrinsic_proto.skills.SkillManifest

# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


id {
  package: "ai.intrinsic"
  name: "control_pinch_gripper"
}
display_name: "Control pinch gripper"
vendor {
  display_name: "Intrinsic"
}
options {
  python_config {
    skill_module: "intrinsic.manipulation.skills.control_pinch_gripper"
    proto_module: "intrinsic.manipulation.skills.control_pinch_gripper_pb2"
    create_skill: "intrinsic.manipulation.skills.control_pinch_gripper.ControlPinchGripper"
  }
}
parameter {
  message_full_name: "intrinsic_proto.skills.PinchGripperCommand"
}
status_info: [
  {
    code: 10200
    title: "Skill Parameterization Error"
    recovery_instructions: "Check and fix skill input parameters."
  },
  {
    code: 10300
    title: "Gripper Service Error"
    recovery_instructions: "Check gripper hardware connection and service status."
  }
]

